"""initial

Revision ID: f97b23098253
Revises: 
Create Date: 2026-05-22 12:42:21.668757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97b23098253'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_memory', sa.Column('role', sa.String(), nullable=True))
    op.add_column('chat_memory', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('chat_memory', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('chat_memory', 'response',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_chat_memory_email'), 'chat_memory', ['email'], unique=False)
    op.add_column('history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('history', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_payments_email'), 'payments', ['email'], unique=False)
    op.create_unique_constraint(None, 'payments', ['payment_id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_email'), table_name='payments')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_column('history', 'created_at')
    op.drop_column('history', 'user_id')
    op.drop_index(op.f('ix_chat_memory_email'), table_name='chat_memory')
    op.alter_column('chat_memory', 'response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('chat_memory', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('chat_memory', 'created_at')
    op.drop_column('chat_memory', 'role')
    # ### end Alembic commands ###
